--THIS USER IS SPECIFIC TO THE DATABASE WHERE THIS SCRIPT IS TO BE RUN AND IT 
--SHOULD BE A USER WITH DBA PRIVS.
--AND ALSO @pentaho should be replaced with the correct instance name

--conn admin/password@pentaho

set escape on;

create tablespace pentaho_tablespace
  logging
  datafile 'ptho_ts.dbf' 
  size 32m 
  autoextend on 
  next 32m maxsize 2048m
  extent management local;

drop user hibuser cascade;
 
create user hibuser identified by "password" default tablespace pentaho_tablespace quota unlimited on pentaho_tablespace temporary tablespace temp quota 5M on system;

grant create session, create procedure, create table to hibuser;

--CREATE ADDITIONAL REPOSITORY TABLES

conn hibuser/password;
CREATE TABLE DATASOURCE(NAME VARCHAR2(50) NOT NULL PRIMARY KEY,MAXACTCONN INTEGER NOT NULL,DRIVERCLASS VARCHAR2(50) NOT NULL,IDLECONN INTEGER NOT NULL,USERNAME VARCHAR2(50) NOT NULL,PASSWORD VARCHAR2(150) NOT NULL,URL VARCHAR2(100) NOT NULL,QUERY VARCHAR2(100) NOT NULL,WAIT INTEGER NOT NULL);
CREATE TABLE USERS(USERNAME VARCHAR2(50) NOT NULL PRIMARY KEY,PASSWORD VARCHAR2(50) NOT NULL,ENABLED NUMBER(1) NOT NULL,DESCRIPTION VARCHAR2(100));
CREATE TABLE AUTHORITIES(AUTHORITY VARCHAR2(50) NOT NULL PRIMARY KEY,DESCRIPTION VARCHAR2(100));
CREATE TABLE GRANTED_AUTHORITIES(USERNAME VARCHAR2(50) NOT NULL,AUTHORITY VARCHAR2(50) NOT NULL,CONSTRAINT FK_GRANTED_AUTH_USERS FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME),CONSTRAINT FK_GRANTED_AUTH_AUTHORITIES FOREIGN KEY(AUTHORITY) REFERENCES AUTHORITIES(AUTHORITY));

commit;